name: Literals
run-name: Run by @${{ github.actor }}
on: push
jobs:
  print:
    name: Super Useful Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO"
        if: ${{ contains(github.run_id,'1') }}
      - run: exit 1
      - run: echo "failure"
        if: ${{ failure() }}
      - run: echo "last"
