name: Environment variables
on: push
env:
  BRANCH: main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${BRANCH}"
      - run: node -v
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - env:
          BRANCH: develop
          run: echo "${BRANCH}"
