name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"SE
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
